logfile: "fifaa.config"

fuse:
  mount: "./fuse_mount"
  root: "./fuse_root"
  fuseFS: "./pFsysFI/pFsysFI/fifaaFS"

benchmark: "./fuse_mount/x"

parameters:
  #- "-i input"
  #- "-o output"
written_file:
        - "./fuse_mount/data.txt"
log_file : "/home/daoce/Downloads/fifaa.log"

injection:
  # we now support multiple injection types:
  # shornwrite, bitflip, dorppedwrite
  inject_flag: 1
  fault_model: "bitflip" 
  num_trials: 2

fault_op:
  bitflip:
    - fifaa_write

  #shornwrite:
  #  - fifaa_write

  #dropwrite:
  #  - fifaa_write

fault_model_spec:
  bitflip:
    consecutive_bits: 2

  #shornwrite:
  #  shorn_portion: 0.1
