logfile: "fifaa.config"

fuse:
  mount: "./fuse_mount"
  root: "./fuse_root"
  fuseFS: "./pFsysFI/pFsysFI/fifaaFS"

benchmark: "x"

parameters:
  - "-i input"
  - "-o output"

injection:
  # we now support multiple injection types:
  # shornwrite, bitflip, dorppedwrite
  inject_flag: 0
  fault_model: "bitflip" 
  num_trials: 100

fault_op:
  bitflip:
    - fiffa_write

  shornwrite:
    - fiffa_write

fault_model_spec:
  bitflip:
    consecutive_bits: 2

  shornwrite:
    shorn_portion: 0.1